### ISSUE TITLE
External Zabbix Proxies reporting Traefik Gateway IP as source

### ISSUE THREAD

**Issue by checkerbomb** [heyValdemar/zabbix-traefik-letsencrypt-docker-compose#4]
Hey, thanks very much for the great resource you've provided here.

I'm running into a minor, but annoying issue. I have a couple Zabbix Proxies running on other networks, and they all report to the Zabbix Server deployed by the Docker Compose file you've provided.

The issue I'm running into is that the Zabbix Server sees all of the proxy IPs as 172.21.0.1, which is the Gateway IP of the Docker 'traefik' network as reported by `docker network inspect traefik`. I get the following error message from the Zabbix Server container's logs: 

`cannot accept connection from proxy "Zabbix proxy ABC" at "172.21.0.1", allowed address: "10.72.96.22": connection is not allowed`

Adding 172.21.0.1 as an address for each proxy at _Administration > Proxies > [proxy] > Proxy address_ takes care of the error message and allows the proxy to start reporting, but this still seems non-optimal. I was running Zabbix Server on baremetal without Traefik prior to this deployment and the proxy IPs were reported correctly on that installation, so I believe the issue here is with Traefik.

I assume that I need another Traefik rule in the Docker Compose file to allow the proxy's true source IP through but I have no idea where to start. Any thoughts?

**Comment by heyvaldemar** [comment]
hey @checkerbomb,

One approach could be to use the Proxy Protocol, which is designed to preserve the original IP addresses through a connection header. You can enable this in Traefik by tweaking your `docker-compose.yml` file. Just add some lines to activate Proxy Protocol for your web and websecure entrypoints. Remember, though, enabling Proxy Protocol without proper security checks can be risky since it trusts incoming header information, which could be spoofed.

If Zabbix itself supports Proxy Protocol, you’ll also need to configure it to understand these headers. However, not all versions of Zabbix might support this directly, so you’d need to check the documentation for your specific version.

Another alternative is using an external load balancer that handles IP preservation better and works well with Docker and Traefik. Some cloud services offer these with built-in support for maintaining client IPs.

If none of these options fit, you might have to consider reworking your network setup. For instance, reconfiguring the placement of Traefik in relation to your Zabbix server might help avoid the IP masking issue.

Lastly, while it's not ideal, setting the Docker gateway IP as the recognized address for all proxies in Zabbix, as you've done, is a valid temporary fix. It's not perfect since it loses the granularity of individual proxy IPs, but it can work while you explore more permanent solutions.

Let's discuss this on our [Discord](https://discord.gg/AJQGCCBcqf) server; it'll be more convenient.
